export default {
  index: 'Overview',
  installation: 'Installation',
  quickstart: 'Quickstart',
  concepts: 'Concepts',
  configuration: 'Configuration',
  'agent-client': 'Agent Client',
  a2a: 'A2A',
  streaming: 'Streaming',
  options: 'Options',
  messages: 'Messages',
  tools: 'Tools & MCP',
  memory: 'Memory & State',
  'multi-agent': 'Multi-Agent',
  swarm: 'Swarm Orchestration',
  workflows: 'Workflows',
  'structured-outputs': 'Structured Outputs',
  'system-prompts': 'System Prompts',
  skills: 'Skills',
  triggers: 'Triggers',
  features: 'Features',
  steward: 'Steward',
  'human-in-the-loop': 'Human-in-the-Loop',
  'desktop-execution': 'Desktop Execution',
  checkpointing: 'Checkpointing',
  'long-running-tasks': 'Long-Running Tasks',
  oauth: 'OAuth Transport',
  environment: 'Environment',
  'deployment-guide': 'Deployment',
  testing: 'Testing',
  examples: 'Examples',
  'api-reference': 'API Reference'
}
